# Generated by Django 4.1.3 on 2022-12-05 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="CSVアフィル", max_length=50)),
                (
                    "upload_dir",
                    models.FileField(
                        upload_to="csv",
                        validators=[
                            django.core.validators.FileExtensionValidator(["csv"])
                        ],
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
